name: ranch_flame
description: Custom additions for Flame for the Very Good Ranch game.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.7
  flame: ^1.25.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.18.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
